export const BLOG_POSTS = [
  {
    id: 1,
    title: { ar: '١٠ أخطاء شائعة في التغذية تمنعك من خسارة الوزن', en: '10 Common Nutrition Mistakes Preventing Weight Loss' },
    excerpt: { ar: 'اكتشف الأخطاء التي يرتكبها معظم الناس عند محاولة إنقاص الوزن وكيف تتجنبها للحصول على نتائج أفضل.', en: 'Discover the mistakes most people make when trying to lose weight and how to avoid them for better results.' },
    category: 'nutrition',
    readTime: { ar: '٥ دقائق', en: '5 min read' },
    date: { ar: '١٥ مارس ٢٠٢٤', en: 'Mar 15, 2024' },
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=500&fit=crop',
    featured: true,
  },
  {
    id: 2,
    title: { ar: 'أفضل ٥ تمارين لحرق الدهون في المنزل', en: 'Top 5 Fat-Burning Home Exercises' },
    excerpt: { ar: 'تمارين فعالة يمكنك ممارستها في المنزل بدون معدات لحرق الدهون وبناء اللياقة البدنية.', en: 'Effective exercises you can do at home without equipment to burn fat and build fitness.' },
    category: 'workout',
    readTime: { ar: '٧ دقائق', en: '7 min read' },
    date: { ar: '١٢ مارس ٢٠٢٤', en: 'Mar 12, 2024' },
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=500&fit=crop',
    featured: true,
  },
  {
    id: 3,
    title: { ar: 'كيف تبني عادات صحية تدوم مدى الحياة', en: 'How to Build Healthy Habits That Last a Lifetime' },
    excerpt: { ar: 'دليل عملي لبناء عادات صحية مستدامة تصبح جزءاً من حياتك اليومية بدون مجهود.', en: 'A practical guide to building sustainable healthy habits that become part of your daily life effortlessly.' },
    category: 'lifestyle',
    readTime: { ar: '٦ دقائق', en: '6 min read' },
    date: { ar: '١٠ مارس ٢٠٢٤', en: 'Mar 10, 2024' },
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&h=500&fit=crop',
    featured: true,
  },
  {
    id: 4,
    title: { ar: 'البروتين: كم تحتاج يومياً لبناء العضلات؟', en: 'Protein: How Much Do You Need Daily to Build Muscle?' },
    excerpt: { ar: 'حساب احتياجك اليومي من البروتين بناءً على وزنك وأهدافك الرياضية.', en: 'Calculate your daily protein needs based on your weight and fitness goals.' },
    category: 'nutrition',
    readTime: { ar: '٤ دقائق', en: '4 min read' },
    date: { ar: '٨ مارس ٢٠٢٤', en: 'Mar 8, 2024' },
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&h=500&fit=crop',
  },
  {
    id: 5,
    title: { ar: 'روتين التمارين المثالي للمبتدئين', en: 'The Perfect Workout Routine for Beginners' },
    excerpt: { ar: 'خطة تمارين أسبوعية مصممة خصيصاً للمبتدئين لبناء أساس قوي.', en: 'A weekly workout plan designed specifically for beginners to build a strong foundation.' },
    category: 'workout',
    readTime: { ar: '٨ دقائق', en: '8 min read' },
    date: { ar: '٥ مارس ٢٠٢٤', en: 'Mar 5, 2024' },
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=500&fit=crop',
  },
  {
    id: 6,
    title: { ar: 'أهمية النوم في رحلة اللياقة البدنية', en: 'The Importance of Sleep in Your Fitness Journey' },
    excerpt: { ar: 'لماذا النوم الجيد أساسي للتعافي وبناء العضلات وخسارة الدهون.', en: 'Why good sleep is essential for recovery, muscle building, and fat loss.' },
    category: 'lifestyle',
    readTime: { ar: '٥ دقائق', en: '5 min read' },
    date: { ar: '٢ مارس ٢٠٢٤', en: 'Mar 2, 2024' },
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=500&fit=crop',
  },
  {
    id: 7,
    title: { ar: 'وجبات صحية سريعة التحضير للمشغولين', en: 'Quick Healthy Meals for Busy People' },
    excerpt: { ar: '١٠ وصفات صحية يمكن تحضيرها في أقل من ١٥ دقيقة للأشخاص المشغولين.', en: '10 healthy recipes you can prepare in under 15 minutes for busy people.' },
    category: 'nutrition',
    readTime: { ar: '٦ دقائق', en: '6 min read' },
    date: { ar: '٢٨ فبراير ٢٠٢٤', en: 'Feb 28, 2024' },
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&h=500&fit=crop',
  },
  {
    id: 8,
    title: { ar: 'كيف تتغلب على ثبات الوزن', en: 'How to Overcome a Weight Loss Plateau' },
    excerpt: { ar: 'استراتيجيات فعالة لكسر حاجز ثبات الوزن والاستمرار في التقدم.', en: 'Effective strategies to break through weight loss plateaus and keep progressing.' },
    category: 'nutrition',
    readTime: { ar: '٧ دقائق', en: '7 min read' },
    date: { ar: '٢٥ فبراير ٢٠٢٤', en: 'Feb 25, 2024' },
    image: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&h=500&fit=crop',
  },
  {
    id: 9,
    title: { ar: 'تمارين الإطالة: لماذا هي مهمة؟', en: 'Stretching Exercises: Why Are They Important?' },
    excerpt: { ar: 'فوائد تمارين الإطالة للتعافي وتجنب الإصابات وتحسين المرونة.', en: 'Benefits of stretching for recovery, injury prevention, and improved flexibility.' },
    category: 'workout',
    readTime: { ar: '٤ دقائق', en: '4 min read' },
    date: { ar: '٢٢ فبراير ٢٠٢٤', en: 'Feb 22, 2024' },
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=500&fit=crop',
  },
]
