'use client'
import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  ar: {
    nav: {
      home: 'الرئيسية',
      books: 'البرامج',
      results: 'النتائج',
      coach: 'الدعم',
      blog: 'المدونة',
      getBooks: 'احصل على البرامج',
    },
    hero: {
      headline1: 'غيّر جسمك خلال 30 يوم',
      headline2: 'مع برنامج FitZone',
      subheadline: 'اختر البرنامج المناسب لك وابدأ بخطة تدريب أو تغذية، أو احصل على الحزمة الكاملة لتغيير جسمك خلال 30 يوم مع متابعة شهر كامل عبر الواتساب.',
      cta1: 'ابدأ الآن',
      cta2: 'شاهد النتائج',
      guarantee1: 'ضمان جودة المحتوى',
      guarantee2: 'متابعة عبر الواتساب',
      guarantee3: 'موثوق ومعتمد',
      rating: '4.9 من 1000+ عميل',
      downloads: 'تحميل',
      review: 'غيّر حياتي!',
    },
    books: {
      badge: 'نظرة داخل البرامج',
      title: 'ابدأ الآن واختر خطتك',
      subtitle: 'اكتشف محتوى كل برنامج قبل الشراء',
      featured: 'الأكثر مبيعاً',
      contents: 'المحتويات',
      buyNow: 'اشتري الآن',
      bundle: 'الباقة الكاملة',
      bundleDesc: 'احصل على البرامج الثلاثة معاً بسعر مخفض',
      getBundle: 'احصل على الباقة',
      save: 'وفّر 30%',
      currency: 'د.إ',
      pageCount: 'صفحة',
      book1: {
        title: 'الدليل الشامل للتنشيف وبناء الجسم',
        subtitle: '+ تحدي الـ30 يوم',
        chapters: ['السر الذي يخفونه عنك المدربين', 'برنامج تدريبي كامل', 'التمارين بالشرح والفيديوهات', 'الكارديو: متى وكيف وكم؟', 'تحدي الـ30 يوم للتنشيف السريع'],
      },
      book2: {
        title: 'الدليل الكامل لخسارة الدهون',
        subtitle: 'نظام غذائي قابل للتطبيق',
        chapters: ['القاعدة الذهبية لخسارة الدهون', 'خطة تقسيم وجباتك خلال اليوم (3 أو 4 أو 5 وجبات)', 'تنظيم أكل الأسبوع وقائمة التسوق', 'وجبة الشيت: كيف تستمتع بدون ما تخرب كل شيء'],
      },
      book3: {
        title: 'جسمك الجديد في 90 يوم',
        subtitle: 'كل اللي تحتاجه في مكان واحد — بدون تخمين، بدون ضياع',
        chapters: ['برنامج تدريب كامل', 'نظام غذائي متكامل', 'تحدي 30 يوم', 'متابعة شخصية عبر الواتساب', 'خطوات واضحة من البداية للنهاية'],
      },
    },
    transformations: {
      badge: 'نتائج حقيقية من عملاء حقيقيين',
      title: 'تحولات مذهلة',
      subtitle: 'شاهد ما حققه عملاؤنا باستخدام نفس البرامج التي ستحصل عليها',
      before: 'قبل',
      after: 'بعد',
      in: 'في',
      days: 'يوم',
      stats: { s1: 'تحول ناجح', s2: 'نسبة الرضا', s3: 'متوسط خسارة الوزن (كجم)', s4: 'يوم للنتائج الأولى' },
    },
    coach: {
      badge: 'فريق من الخبراء',
      title: 'فريقك في رحلة التحول',
      name: 'فريق FitZone',
      bio: 'فريق متخصص من خبراء التغذية والتدريب. جمعنا أفضل الخبرات لنقدم لك برامج علمية مجربة تساعدك على تحقيق أهدافك بطريقة صحيحة ومستدامة.',
      videoLabel: 'تعرف على الفريق',
      cred1: 'خبراء تغذية ولياقة',
      cred1sub: 'Nutrition & Fitness Experts',
      cred2: 'دعم واتساب شخصي',
      cred2sub: 'Personal WhatsApp Support',
      stat1: 'خبراء متخصصون',
      stat1sub: 'في التغذية واللياقة',
      stat2: '+1000 عميل',
      stat2sub: 'حققوا أهدافهم',
      stat3: '3 برامج متكاملة',
      stat3sub: 'تدريب + تغذية + متابعة',
      stat4: '4.9 تقييم',
      stat4sub: 'من العملاء',
    },
    faq: {
      badge: 'أسئلة شائعة',
      title: 'هل لديك أسئلة؟',
      subtitle: 'إليك أكثر الأسئلة شيوعاً من عملائنا. لم تجد إجابتك؟ تواصل معنا مباشرة.',
      whatsapp: 'تواصل عبر واتساب',
      q1: 'كيف أستلم البرامج بعد الشراء؟',
      a1: 'فور إتمام الدفع، ستصلك رسالة على بريدك الإلكتروني تحتوي على رابط تحميل مباشر للبرامج بصيغة PDF. كما سيتم إرسال نسخة عبر واتساب للتأكيد. التحميل متاح مدى الحياة.',
      q2: 'هل البرامج مناسبة للمبتدئين تماماً؟',
      a2: 'نعم! صممت البرامج لتكون شاملة ومفصلة. تبدأ من الأساسيات وتتدرج للمستويات المتقدمة.',
      q3: 'هل يوجد دعم بعد الشراء؟',
      a3: 'بالتأكيد! يمكنك التواصل مع فريق FitZone مباشرة عبر واتساب لأي استفسار. نجيب على جميع الأسئلة خلال 24 ساعة.',
      q4: 'ما هي طرق الدفع المتاحة؟',
      a4: 'نقبل جميع البطاقات الائتمانية (Visa, Mastercard)، Apple Pay، وكذلك التحويل البنكي المباشر.',
      q5: 'هل يمكنني استرداد المال؟',
      a5: 'بما أن البرامج منتجات رقمية، جميع المبيعات نهائية بعد التحميل. لكن إذا واجهت مشكلة تقنية تمنعك من فتح الملفات، تواصل معنا خلال 7 أيام وسنحل المشكلة أو نرد المبلغ.',
      q6: 'هل أحتاج معدات رياضية خاصة؟',
      a6: 'البرامج تتضمن تمارين منزلية بدون معدات وأخرى للجيم. يمكنك البدء بتمارين وزن الجسم في المنزل.',
    },
    cta: {
      title: 'جاهز لبدء رحلة التحول؟',
      subtitle: 'انضم لأكثر من 1000 شخص غيّروا حياتهم. ابدأ اليوم واحصل على النتائج التي تستحقها.',
      button: 'احصل على الباقة الكاملة',
      g1: 'ضمان الجودة',
      g2: 'دعم مباشر',
      g3: 'تحديثات مجانية',
    },
    footer: {
      desc: 'برامج تدريبية متخصصة في التغذية والتمارين الرياضية. نساعدك على تحقيق أهدافك الصحية.',
      booksTitle: 'البرامج',
      linksTitle: 'روابط',
      legalTitle: 'قانوني',
      privacy: 'سياسة الخصوصية',
      terms: 'الشروط والأحكام',
      refund: 'سياسة الاسترداد',
      aboutCoach: 'عن الفريق',
      successStories: 'قصص النجاح',
      contact: 'تواصل معنا',
      copyright: '© 2025 FitZone. جميع الحقوق محفوظة',
      securePay: 'دفع آمن',
      bankTransfer: 'تحويل بنكي',
    },
    booksPage: {
      badge: 'البرامج التدريبية',
      title: 'ابدأ الآن واختر خطتك',
      subtitle: 'برامج تدريبية متخصصة صممت بعناية لمساعدتك في تحقيق أهدافك الصحية واللياقية.',
      bestSeller: 'الأكثر مبيعاً',
      contents: 'المحتويات',
      pages: 'صفحة',
      currency: 'د.إ',
      discount: 'خصم',
      buyNow: 'اشتري الآن',
      bundle: 'الباقة الكاملة',
      bundleSave: 'وفّر 30%',
      bundleDesc: 'احصل على البرامج الثلاثة معاً بسعر مخفض',
      getBundle: 'ابدأ تحولك اليوم',
      securePay: 'دفع آمن 100%',
      securePayDesc: 'معاملات مشفرة ومحمية بالكامل',
      instantDownload: 'تحميل فوري',
      instantDownloadDesc: 'استلم البرامج فور إتمام الدفع',
      qualityGuarantee: 'ضمان الجودة',
      qualityGuaranteeDesc: 'دعم فني وتحديثات مجانية مدى الحياة',
      added: 'تمت إضافة',
      removed: 'تمت إزالة',
      toCart: 'إلى السلة',
      fromCart: 'من السلة',
    },
    resultsPage: {
      badge: 'قصص نجاح حقيقية',
      title: 'نتائج عملائنا',
      subtitle: 'أكثر من 1000 شخص غيّروا حياتهم باستخدام برامجنا. شاهد قصصهم الملهمة واكتشف كيف يمكنك تحقيق نفس النتائج.',
      before: 'قبل',
      after: 'بعد',
      years: 'سنة',
      kg: 'كجم',
      kgMuscle: 'كجم عضل',
      ctaTitle: 'جاهز لتكون قصة النجاح القادمة؟',
      ctaDesc: 'انضم لأكثر من 1000 شخص حققوا أهدافهم. ابدأ رحلتك اليوم مع برامجنا المتخصصة.',
      ctaButton: 'تصفح البرامج الآن',
      stat1: '+1000',
      stat1Label: 'تحول ناجح',
      stat2: '98%',
      stat2Label: 'نسبة الرضا',
      stat3: '-12',
      stat3Label: 'متوسط خسارة الوزن (كجم)',
      stat4: '60',
      stat4Label: 'يوم للنتائج الأولى',
    },
    blogPage: {
      badge: 'المدونة',
      title: 'نصائح ومقالات',
      subtitle: 'مقالات متخصصة في التغذية والتمارين ونمط الحياة الصحي لمساعدتك في رحلتك.',
      searchPlaceholder: 'ابحث في المقالات...',
      all: 'الكل',
      nutrition: 'التغذية',
      workout: 'التمارين',
      lifestyle: 'نمط الحياة',
      featured: 'مقالات مميزة',
      allArticles: 'جميع المقالات',
      readMore: 'اقرأ المزيد',
      read: 'اقرأ',
      noResults: 'لا توجد نتائج',
      noResultsDesc: 'جرب البحث بكلمات مختلفة أو اختر تصنيف آخر',
      newsletter: 'اشترك في النشرة البريدية',
      newsletterDesc: 'احصل على أحدث المقالات والنصائح مباشرة في بريدك الإلكتروني كل أسبوع.',
      emailPlaceholder: 'بريدك الإلكتروني',
      subscribe: 'اشترك الآن',
    },
    checkout: {
      title: 'إتمام الشراء',
      orderSummary: 'ملخص الطلب',
      total: 'الإجمالي',
      contactInfo: 'معلومات التواصل',
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف (واتساب)',
      paymentMethod: 'طريقة الدفع',
      card: 'بطاقة ائتمانية',
      applePay: 'Apple Pay',
      bankTransfer: 'تحويل بنكي',
      cardNumber: 'رقم البطاقة',
      expiry: 'تاريخ الانتهاء',
      cvv: 'CVV',
      payNow: 'ادفع الآن',
      processing: 'جاري المعالجة...',
      secure: 'معاملة آمنة ومشفرة',
      backToBooks: 'العودة للبرامج',
      success: 'تم الشراء بنجاح!',
      successMsg: 'شكراً لك! سيتم إرسال البرامج إلى بريدك الإلكتروني خلال دقائق.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      books: 'Programs',
      results: 'Results',
      coach: 'Support',
      blog: 'Blog',
      getBooks: 'Get Programs',
    },
    hero: {
      headline1: 'Transform Your Body in 30 Days',
      headline2: 'With FitZone Program',
      subheadline: 'Choose the right program and start with a workout or nutrition plan, or get the complete bundle to transform your body in 30 days with a full month of WhatsApp support.',
      cta1: 'Start Now',
      cta2: 'See Results',
      guarantee1: 'Quality Guaranteed',
      guarantee2: 'WhatsApp Support',
      guarantee3: 'Trusted & Certified',
      rating: '4.9 from 1000+ clients',
      downloads: 'downloads',
      review: 'Changed my life!',
    },
    books: {
      badge: 'Inside The Programs',
      title: 'Start Now & Choose Your Plan',
      subtitle: 'Discover the content of each program before buying',
      featured: 'Best Seller',
      contents: 'Contents',
      buyNow: 'Buy Now',
      bundle: 'Complete Bundle',
      bundleDesc: 'Get all three programs together at a discounted price',
      getBundle: 'Get The Bundle',
      save: 'Save 30%',
      currency: 'AED',
      pageCount: 'pages',
      book1: {
        title: 'Complete Guide to Cutting & Building',
        subtitle: '+ 30-Day Challenge',
        chapters: ["The Secret Trainers Don't Tell You", 'Complete Training Program', 'Exercises with Explanation & Videos', 'Cardio: When, How & How Much?', '30-Day Fast Cutting Challenge'],
      },
      book2: {
        title: 'Complete Fat Loss Guide',
        subtitle: 'Practical Nutrition System',
        chapters: ['The Golden Rule of Fat Loss', 'Daily Meal Split Plan (3, 4, or 5 meals)', 'Weekly Eating Plan & Shopping List', 'Cheat Meal: How to Enjoy Without Ruining Everything'],
      },
      book3: {
        title: 'Your New Body in 90 Days',
        subtitle: 'Everything you need in one place — no guessing, no confusion',
        chapters: ['Complete Training Program', 'Full Nutrition System', '30-Day Challenge', 'Personal WhatsApp Support', 'Clear Steps from Start to Finish'],
      },
    },
    transformations: {
      badge: 'Real Results From Real Clients',
      title: 'Amazing Transformations',
      subtitle: 'See what our clients achieved using the same programs you will get',
      before: 'Before',
      after: 'After',
      in: 'in',
      days: 'days',
      stats: { s1: 'Successful Transformations', s2: 'Satisfaction Rate', s3: 'Avg Weight Loss (kg)', s4: 'Days to First Results' },
    },
    coach: {
      badge: 'Meet Our Expert Team',
      title: 'Your Team for Transformation',
      name: 'FitZone Team',
      bio: 'A specialized team of nutrition and training experts. We combined the best expertise to offer you scientifically proven programs that help you achieve your goals correctly and sustainably.',
      videoLabel: 'Meet The Team',
      cred1: 'Nutrition & Fitness Experts',
      cred1sub: 'Specialized & Certified',
      cred2: 'Personal WhatsApp Support',
      cred2sub: 'Always Here for You',
      stat1: 'Specialized Experts',
      stat1sub: 'In Nutrition & Fitness',
      stat2: '1000+ Clients',
      stat2sub: 'Achieved Their Goals',
      stat3: '3 Complete Programs',
      stat3sub: 'Training + Nutrition + Support',
      stat4: '4.9 Rating',
      stat4sub: 'From Clients',
    },
    faq: {
      badge: 'FAQ',
      title: 'Have Questions?',
      subtitle: "Here are the most common questions. Didn't find your answer? Contact us directly.",
      whatsapp: 'Contact via WhatsApp',
      q1: 'How do I receive the programs?',
      a1: 'Immediately after payment, you will receive an email with a direct download link for the programs in PDF format. Download is available for life.',
      q2: 'Are the programs suitable for beginners?',
      a2: 'Yes! The programs are comprehensive and detailed. They start from basics and progress to advanced levels.',
      q3: 'Is there support after purchase?',
      a3: 'Absolutely! You can contact the FitZone team directly via WhatsApp for any questions. We answer all questions within 24 hours.',
      q4: 'What payment methods are available?',
      a4: 'We accept all credit cards (Visa, Mastercard), Apple Pay, and direct bank transfer.',
      q5: 'Can I get a refund?',
      a5: 'Since the programs are digital products, all sales are final after download. However, if you experience a technical issue that prevents you from opening the files, contact us within 7 days and we will resolve it or issue a refund.',
      q6: 'Do I need gym equipment?',
      a6: 'The programs include home exercises without equipment and others for the gym.',
    },
    cta: {
      title: 'Ready to Start Your Transformation?',
      subtitle: 'Join over 1000 people who changed their lives. Start today and get the results you deserve.',
      button: 'Get The Complete Bundle',
      g1: 'Quality Guarantee',
      g2: 'Direct Support',
      g3: 'Free Updates',
    },
    footer: {
      desc: 'Specialized training programs in nutrition and exercise. We help you achieve your health goals.',
      booksTitle: 'Programs',
      linksTitle: 'Links',
      legalTitle: 'Legal',
      aboutCoach: 'Our Team',
      successStories: 'Success Stories',
      contact: 'Contact Us',
      copyright: '© 2025 FitZone. All rights reserved',
      securePay: 'Secure Payment',
      bankTransfer: 'Bank Transfer',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      refund: 'Refund Policy',
    },
    booksPage: {
      badge: 'Training Programs',
      title: 'Start Now & Choose Your Plan',
      subtitle: 'Specialized training programs carefully designed to help you achieve your health and fitness goals.',
      bestSeller: 'Best Seller',
      contents: 'Contents',
      pages: 'pages',
      currency: 'AED',
      discount: 'Off',
      buyNow: 'Buy Now',
      bundle: 'Complete Bundle',
      bundleSave: 'Save 30%',
      bundleDesc: 'Get all three programs together at a discounted price',
      getBundle: 'Start Your Transformation',
      securePay: '100% Secure Payment',
      securePayDesc: 'Fully encrypted and protected transactions',
      instantDownload: 'Instant Download',
      instantDownloadDesc: 'Receive programs immediately after payment',
      qualityGuarantee: 'Quality Guarantee',
      qualityGuaranteeDesc: 'Free technical support and lifetime updates',
      added: 'Added',
      removed: 'Removed',
      toCart: 'to cart',
      fromCart: 'from cart',
    },
    resultsPage: {
      badge: 'Real Success Stories',
      title: 'Our Clients Results',
      subtitle: 'Over 1000 people changed their lives using our programs. See their inspiring stories and discover how you can achieve the same results.',
      before: 'Before',
      after: 'After',
      years: 'yrs',
      kg: 'kg',
      kgMuscle: 'kg muscle',
      ctaTitle: 'Ready to Be The Next Success Story?',
      ctaDesc: 'Join over 1000 people who achieved their goals. Start your journey today with our specialized programs.',
      ctaButton: 'Browse Programs Now',
      stat1: '1000+',
      stat1Label: 'Successful Transformations',
      stat2: '98%',
      stat2Label: 'Satisfaction Rate',
      stat3: '-12',
      stat3Label: 'Avg Weight Loss (kg)',
      stat4: '60',
      stat4Label: 'Days to First Results',
    },
    blogPage: {
      badge: 'Blog',
      title: 'Tips & Articles',
      subtitle: 'Specialized articles in nutrition, exercise, and healthy lifestyle to help you on your journey.',
      searchPlaceholder: 'Search articles...',
      all: 'All',
      nutrition: 'Nutrition',
      workout: 'Workout',
      lifestyle: 'Lifestyle',
      featured: 'Featured Articles',
      allArticles: 'All Articles',
      readMore: 'Read More',
      read: 'Read',
      noResults: 'No Results',
      noResultsDesc: 'Try different keywords or choose another category',
      newsletter: 'Subscribe to Our Newsletter',
      newsletterDesc: 'Get the latest articles and tips delivered to your email every week.',
      emailPlaceholder: 'Your email',
      subscribe: 'Subscribe Now',
    },
    checkout: {
      title: 'Checkout',
      orderSummary: 'Order Summary',
      total: 'Total',
      contactInfo: 'Contact Information',
      name: 'Full Name',
      email: 'Email',
      phone: 'Phone Number (WhatsApp)',
      paymentMethod: 'Payment Method',
      card: 'Credit Card',
      applePay: 'Apple Pay',
      bankTransfer: 'Bank Transfer',
      cardNumber: 'Card Number',
      expiry: 'Expiry Date',
      cvv: 'CVV',
      payNow: 'Pay Now',
      processing: 'Processing...',
      secure: 'Secure & encrypted transaction',
      backToBooks: 'Back to Programs',
      success: 'Purchase Successful!',
      successMsg: 'Thank you! The programs will be sent to your email within minutes.',
    },
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ar')

  useEffect(() => {
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
  }, [lang])

  const t = (key) => {
    const keys = key.split('.')
    let value = translations[lang]
    for (const k of keys) {
      value = value?.[k]
    }
    return value || key
  }

  const toggleLang = () => {
    setLang(prev => prev === 'ar' ? 'en' : 'ar')
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
